### ISSUE TITLE
Documentation for CDDDocker

### ISSUE THREAD

**Issue by QuinnCiccoretti** [aws-samples/aws-greengrass-lambda-functions#320]
I would like to pull containers from ECR without giving my AWS credentials to an edge device, or at least without giving that device more permissions than needed. Is there any documentation on how CDDDocker gets credentials/authorization to pull from ECR?

**Comment by timmattison** [comment]
In the case of CDDDocker it gets the AWS credentials from a Greengrass feature called the Token Exchange Service (TES). This service is tied into the Greengrass Core SDKs that you use in your Greengrass Lambda functions. As long as you are using the Greengrass Core SDKs instead of the regular AWS SDKs in your Lambda functions you'll automatically get temporary credentials for calls to any AWS service. Those temporary credentials will have the permissions that you've assigned to the role for your Greengrass Core.

Here are examples for the various SDKs:

- [NodeJS TES example](https://github.com/aws/aws-greengrass-core-sdk-js/tree/master/greengrassExamples/TES)
- [Java TES example](https://github.com/aws/aws-greengrass-core-sdk-java/tree/master/samples/TES)
- [Python TES example](https://github.com/aws/aws-greengrass-core-sdk-python/tree/master/examples/TES)
- [C TES example](https://github.com/aws/aws-greengrass-core-sdk-c/tree/master/aws-greengrass-core-sdk-c-example/tes)

**Comment by QuinnCiccoretti** [comment]
Wow, this is really awesome. You said

> As long as you are using the Greengrass Core SDKs instead of the regular AWS SDKs in your Lambda functions you'll automatically get temporary credentials 

But it seems [the node code imports the regular aws-sdk](https://github.com/aws/aws-greengrass-core-sdk-js/blob/master/greengrassExamples/TES/index.js#L9).
The python, java and c versions do much the same. Can I get clarification on what you mean?
Also, does the provisioner automatically authorize policies to ECR and other services?
I assume thats what these logs indicate:

> [INFO] BasicDeploymentHelper: - arn:aws:iam::aws:policy/AWSLambdaReadOnlyAccess
> [INFO] BasicDeploymentHelper: - arn:aws:iam::aws:policy/AWSIoTFullAccess
> [INFO] BasicDeploymentHelper: - arn:aws:iam::aws:policy/AWSGreengrassFullAccess
> [INFO] BasicDeploymentHelper: - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
> [INFO] BasicDeploymentHelper: - arn:aws:iam::aws:policy/AmazonSageMakerReadOnly
> [INFO] BasicDeploymentHelper: - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
> [INFO] BasicDeploymentHelper: - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly

**Comment by timmattison** [comment]
Apologies, I misspoke there. You need to use the Greengrass Core SDKs to get access to the local versions of certain features (publishing to Greengrass Core instead of directly to IoT Core, local shadows, local secrets manager, etc). The other features are accessed with the normal SDKs.

Greengrass emulates the Amazon ECS container credential provider. In the environment for a Greengrass Lambda function a few variables are set that tell the SDK, if it is using the [default credential provider chain](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-default), to try to get credentials from an endpoint that acts the same as the ECS container credentials provider. These are temporary credentials that have the same permissions as the Greengrass core's role.

As long as your SDK is set to use the default credentials provider chain then you should be able to use any service in a Lambda function. But for services that have a local equivalent you need to use the Greengrass Core SDK.

**Comment by timmattison** [comment]
And yes, the provisioner does add the permissions you see in the logs to the Greengrass core's role. Those permissions are actually set up in the [deployments.defaults.conf](https://github.com/aws-samples/aws-greengrass-lambda-functions/blob/master/deployments/deployment.defaults.conf) so you can modify them if you need to.

**Comment by QuinnCiccoretti** [comment]
Makes sense. I was a able to acess ECR without extra authentication presumably because the ECR client uses the default credential provider chain. And now I understand how it works!
